app/models/base.py
# -*- coding: utf-8 -*-

from datetime import datetime

from flask import abort

from app import context
from app.extenions import db
from .mc import cache, clear_mc

MC_KEY_ITEM_BY_ID = '%s:%s'

_redis = None

class BaseModel(db.Model):
    __abstract__ = True

    _redis = None

    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    @property
    def url(self):
        return f'/{self.__class__.__name__.lower()}/{self.id}/'

    @property
    def redis(self):
        global _redis
        if _redis is None:
            _redis = context.get('redis')
        return _redis

    @classmethod
    def get_or_create(cls, **kwargs):
        instance = cls.query.filter_by(**kwargs).first()
        if instance:
            return instance, False
        return cls.create(**kwargs), True

    def get_db_key(self, key):
        return f'{self.__class__.__name__}/{self.id}/props/{key}'

    def set_props_by_key(self, key, value):
        key = self.get_db_key(key)
        return self.redis.set(key, value)

    def get_props_by_key(self, key):
        key = self.get_db_key(key)
        return self.redis.get(key) or b''

    @classmethod
    def get_or_404(cls, id):
        obj = cls.cache(id)
        if not obj:
            abort(404)
        return obj

    @classmethod
    @cache(MC_KEY_ITEM_BY_ID % ('{cls.__name__}', '{id}'))
    def cache(cls, id):
        return cls.query.get(id)

    @classmethod
    def get_multi(cls, ids):
        return [cls.cache(id) for id in ids]

    @classmethod
    def create(cls, **kwargs):
        instance = cls(**kwargs)
        db.session.add(instance)
        db.session.commit()
        cls.__flush__(instance)
        return instance

    def save(self):
        db.session.add(self)
        db.session.commit()
        self.__flush__(self)

    def delete(self):
        db.session.delete(self)
        db.session.commit()
        self.__flush__(self)

    @classmethod
    def __flush__(cls, target):
        clear_mc(MC_KEY_ITEM_BY_ID % (target.__class__.__name__, target.id))
        target.clear_mc()

    def clear_mc(self):
        ...

app/models/comment.py
# -*- coding: utf-8 -*-

import mistune

from app.extenions import db
from app.models.base import BaseModel
from .consts import K_COMMENT, ONE_HOUR
from .mc import clear_mc, cache
from .react import ReactMixin, ReactItem
from .signals import comment_reacted
from .user import GithubUser

markdown = mistune.Markdown()
MC_KEY_COMMENT_LIST = 'comment:%s:comment_list'
MC_KEY_N_COMMENTS = 'comment:%s:n_comments'
MC_KEY_COMMENT_IDS_LIKED_BY_USER = 'react:comment_ids_liked_by:%s:%s'


class Comment(ReactMixin, BaseModel):
    __tablename__ = 'comments'

    github_id = db.Column(db.Integer)
    post_id = db.Column(db.Integer)
    reaction_type = db.Column(db.Integer)
    ref_id = db.Column(db.Integer)
    kind = K_COMMENT

    @property
    def content(self):
        rv = self.get_props_by_key('content')
        if rv:
            return rv.decode('utf-8')

    @property
    def html_content(self):
        content = self.content
        if not content:
            return ''
        return markdown(content)

    @property
    def user(self):
        return GithubUser.query.filter_by(gid=self.github_id).first()

    @property
    def n_likes(self):
        return self.stats.love_count

    def set_content(self, content):
        return self.set_props_by_key('content', content)

    def save(self, *args, **kwargs):
        content = kwargs.pop('content', None)
        if content is not None:
            self.set_content(content)
        return super().save()

    def clear_mc(self):
        for key in (MC_KEY_N_COMMENTS, MC_KEY_COMMENT_LIST):
            clear_mc(key % self.post_id)


class CommentMixin:
    def add_comment(self, user_id, content, ref_id=0):
        obj = Comment.create(github_id=user_id, post_id=self.id,
                             ref_id=ref_id)
        obj.set_content(content)
        return obj

    def del_comment(self, user_id, comment_id):
        c = Comment.query.get(comment_id)
        if c and c.github_id == user_id and c.post_id == self.id:
            c.delete()
            return True
        return False

    @property
    @cache(MC_KEY_COMMENT_LIST % ('{self.id}'))
    def comments(self):
        return Comment.query.filter_by(post_id=self.id).order_by(
            Comment.id.desc()).all()

    @property
    @cache(MC_KEY_N_COMMENTS % ('{self.id}'))
    def n_comments(self):
        return Comment.query.filter_by(post_id=self.id).count()

    @cache(MC_KEY_COMMENT_IDS_LIKED_BY_USER % (
            '{user_id}', '{self.id}'), ONE_HOUR)
    def comment_ids_liked_by(self, user_id):
        cids = [c.id for c in self.comments]
        if not cids:
            return []
        queryset = ReactItem.query.filter(
            ReactItem.user_id == user_id, ReactItem.target_id.in_(cids),
            ReactItem.target_kind == K_COMMENT).all()
        return [item.target_id for item in queryset]


@comment_reacted.connect
def update_comment_list_cache(_, user_id, comment_id):
    comment = Comment.cache(comment_id)
    if comment:
        clear_mc(MC_KEY_COMMENT_LIST % comment.post_id)
        clear_mc(MC_KEY_COMMENT_IDS_LIKED_BY_USER % (
            user_id, comment.post_id))

app/models/utils.py
# -*- coding: utf-8 -*-

import math


class Empty:

    def __call__(self, *a, **kw):
        return empty

    def __nonzero__(self):
        return False

    def __contains__(self, item):
        return False

    def __repr__(self):
        return '<Empty Object>'

    def __str__(self):
        return ''

    def __eq__(self, v):
        return isinstance(v, Empty)

    def __getattr__(self, name):
        if not name.startswith('__'):
            return empty
        raise AttributeError(name)

    def __len__(self):
        return 0

    def __getitem__(self, key):
        return empty

    def __setitem__(self, key, value):
        pass

    def __delitem__(self, key):
        pass

    def __iter__(self):
        return self

    def __next__(self):
        raise StopIteration

    def next(self):
        raise StopIteration

    def __getattr__(self, item):
        return ''

    def __setattr__(self, key, value):
        return self

    def __delattr__(self, item):
        return self


empty = Empty()


def trunc_utf8(string, num, etc='...'):
    if num >= len(string):
        return string

    if etc:
        trunc_idx = num - len(etc)
    else:
        trunc_idx = num
    ret = string[:trunc_idx]
    if etc:
        ret += etc
    return ret


class AttrDict(dict):
    def __init__(self, *args, **kwargs):
        super(AttrDict, self).__init__(*args, **kwargs)
        self.__dict__ = self


class Pagination:
    def __init__(self, page, per_page, total):
        self.page = page
        self.per_page = per_page
        self.total = total

    @property
    def pages(self):
        if self.per_page == 0 or self.total is None:
            pages = 0
        else:
            pages = int(math.ceil(self.total / float(self.per_page)))
        return pages

    @property
    def prev_num(self):
        if not self.has_prev:
            return None
        return self.page - 1

    @property
    def has_prev(self):
        return self.page > 1

    @property
    def has_next(self):
        return self.page < self.pages

    @property
    def next_num(self):
        if not self.has_next:
            return None
        return self.page + 1

    def iter_pages(self, left_edge=2, left_current=2,
                   right_current=2, right_edge=2):
        last = 0
        for num in range(1, self.pages + 1):
            if num <= left_edge or \
                    (num > self.page - left_current - 1 and
                     num < self.page + right_current) or \
                    num > self.pages - right_edge:
                if last + 1 != num:
                    yield None
                yield num
                last = num

app/views/blog.py
# -*- coding: utf-8 -*-

from collections import Counter
from itertools import groupby

from flask import Blueprint, render_template, session, abort, current_app
from flask_login import login_required

from app.models import Post, PostTag, Tag
from app.models.mc import cache
from app.models.profile import get_profile
from app.models.utils import Pagination
from app.models.blog import (MC_KEY_ARCHIVES, MC_KEY_ARCHIVE, MC_KEY_TAGS,
                             MC_KEY_TAG)

bp = Blueprint('blog', __name__, url_prefix='/')


@bp.route('/')
def index():
    return _posts()


def _posts(page=1):
    PER_PAGE = current_app.config.get('PER_PAGE')
    start = (page - 1) * PER_PAGE
    posts = Post.get_all(with_page=False)
    total = len(posts)
    posts = posts[start: start + PER_PAGE]
    paginator = Pagination(page, PER_PAGE, total)
    profile = get_profile()

    return render_template('index.html', posts=posts, paginator=paginator,
                           profile=profile)


@bp.route('/post/<ident>/')
def post(ident):
    return _post(ident=ident)


@bp.route('/page/<ident>/')
def page(ident=1):
    if str(ident).isdigit():
        return _posts(page=int(ident))
    return _post(ident=ident)


def _post(ident, is_preview=False):
    post = Post.get_or_404(ident)
    if not is_preview and post.status != Post.STATUS_ONLINE:
        abort(404)
    github_user = session.get('user')
    stats = post.stats
    reaction_type = None
    liked_comment_ids = []
    if github_user:
        reaction_type = post.get_reaction_type(github_user['gid'])

        liked_comment_ids = post.comment_ids_liked_by(
            github_user['gid'])
    related_posts = post.get_related()
    return render_template('post.html', post=post, github_user=github_user,
                           stats=stats, reaction_type=reaction_type,
                           liked_comment_ids=liked_comment_ids,
                           related_posts=related_posts)


@bp.route('/post/<ident>/preview')
# @login_required
def preview(ident):
    return _post(ident=ident, is_preview=True)


@bp.route('/archives')
@cache(MC_KEY_ARCHIVES)
def archives():
    rv = {
        year: list(items) for year, items in groupby(
        Post.query.filter_by(status=Post.STATUS_ONLINE).order_by(
            Post.id.desc()).all(),
        lambda item: item.created_at.year)
    }
    archives = sorted(rv.items(), key=lambda x: x[0],
                      reverse=True)
    return render_template('archives.html', archives=archives)


@bp.route('/archive/<year>')
@cache(MC_KEY_ARCHIVE % '{year}')
def archive(year):
    posts = Post.query.filter(Post.status == Post.STATUS_ONLINE,
                              Post.created_at >= f'{year}-01-01',
                              Post.created_at < f'{int(year) + 1}-01-01').order_by(
        Post.id.desc()).all()
    archives = [(year, posts)]
    return render_template('archives.html', archives=archives)


@bp.route('/tags')
@cache(MC_KEY_TAGS)
def tags():
    tag_ids = PostTag.query.with_entities(PostTag.tag_id).all()
    counter = Counter(tag_ids)
    tags_ = Tag.get_multi(counter.keys())
    tags = [(tags_[index], count)
            for index, count in enumerate(counter.values())]

    return render_template('tags.html', tags=tags)


@bp.route('/tag/<int:tag_id>/')
@cache(MC_KEY_TAG % '{tag_id}')
def tag(tag_id):
    tag = Tag.cache(tag_id)
    post_ids = PostTag.query.filter_by(tag_id=tag_id).order_by(
        PostTag.post_id.desc()).with_entities(PostTag.post_id).all()
    posts = Post.get_multi(post_ids)
    return render_template('tag.html', tag=tag, posts=posts)

app/views/utils.py
# -*- coding: utf-8 -*-

from werkzeug.utils import find_modules, import_string


def register_blueprint(root, app):
    for name in find_modules(root, recursive=True):
        mod = import_string(name)
        if hasattr(mod, 'bp'):
            app.register_blueprint(mod.bp)

app/templates/archives.html
{% extends 'base.html' %}

{% block content %}
    <section class="post page archives">
    {% for year, posts in archives %}
        <h3 class="archive-year-wrap">
            <a href="{{ url_for('blog.archive', year=year) }}"
               class="archive-year">
                {{ year }}
            </a>
        </h3>

        <div class="archives">
            {% for post in posts %}
                <div class="archive">
                    <a class="post-go" href="{{ post.url }}">
                        <div>
          <span class="date">
            {{ post.created_at.strftime('%m-%d') }}
          </span>
                            <span class="slash">/</span>
                            {{ post.title }}
                        </div>
                    </a>
                </div>
            {% endfor %}

        </div>
    {% endfor %}


{% endblock %}

{% block pagination %}

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, height=device-height, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <title>
        {% block title %}M-in's Blog{% endblock %}
    </title>
    {% block doc_head %}
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/main.min.css') }}">

        {% block more_head %}
        {% endblock %}
    {% endblock %}
</head>
<body>
<div class="nav-container">
    <nav class="home-menu pure-menu pure-menu-horizontal">
        <a class="pure-menu-heading" href="/">
            <span class="title">我的博客</span>
        </a>

        <ul class="pure-menu-list clearfix">
            {% for endpoint_or_url, name in SITE_NAV_MENUS %}
                {% set url = url_for(endpoint_or_url) if '.' in endpoint_or_url else endpoint_or_url %}
                <li class="pure-menu-item {{ 'actived' if request.path == url else '' }}">
                    <a href="{{ url }}" class="pure-menu-link">{{ name }}</a>
                </li>
            {% endfor %}
        </ul>
    </nav>
</div>

<div class="container" id="content-outer">
    <div class="inner" id="content-inner">
        {% block content %}
        {% endblock %}
    </div>
    {% block pagination %}

    {% endblock %}
</div>

<footer class="footer text-center">
    <div id="bottom-inner">
        <a class="bottom-item" href="/">首页</a> |
        <a class="bottom-item" href="https://github.com/Lovemma/Gatsby"
           target="_blank">GitHub</a> |
        Powered by
        <a class="href-item" href="https://github.com/pallets/flask"
           target="_blank">Flask</a>
        | Theme inspired by <a class="href-item"
                               href="https://github.com/KevinOfNeu/hexo-theme-xoxo"
                               target="_blank">hexo-theme-xoxo</a>
    </div>
</footer>

{% block bottom_script %}
{% endblock %}

</body>
</html>

app/templates/comment.html
{% macro render_single_comment(comment, github_user) %}
    {% set user = comment.user %}
    <li class="gitment-comment">
        <a class="gitment-comment-avatar"
           href="{{ user.link }}" target="_blank">
            <img class="gitment-comment-avatar-img"
                 src="{{ user.picture }}">
        </a>
        <div class="gitment-comment-main">
            <div class="gitment-comment-header">
                <a class="gitment-comment-name"
                   href="{{ user.link if comment.user else '#' }}"
                   target="_blank">
                    {{ user.username }}
                </a>
                commented on
                <span title="{{ comment.created_at }}">{{ comment.created_at.strftime('%a %B %d, %Y') }}</span>
                {% if github_user %}
                    <div class="gitment-comment-like-btn {{ 'liked' if github_user['id'] == user.id else '' }}"
                         data-id={{ comment.id }}>
                        <svg class="gitment-heart-icon"
                             xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 50 50">
                            <path d="M25 39.7l-.6-.5C11.5 28.7 8 25 8 19c0-5 4-9 9-9 4.1 0 6.4 2.3 8 4.1 1.6-1.8 3.9-4.1 8-4.1 5 0 9 4 9 9 0 6-3.5 9.7-16.4 20.2l-.6.5zM17 12c-3.9 0-7 3.1-7 7 0 5.1 3.2 8.5 15 18.1 11.8-9.6 15-13 15-18.1 0-3.9-3.1-7-7-7-3.5 0-5.4 2.1-6.9 3.8L25 17.1l-1.1-1.3C22.4 14.1 20.5 12 17 12z"></path>
                        </svg>
                        <span>0</span></div>
                {% endif %}
            </div>
            <div class="gitment-comment-body gitment-markdown">{{ comment.html_content|safe }}
            </div>
        </div>
    </li>
{% endmacro %}

{% macro render_comments(comments, github_user) %}
    {% for comment in comments %}
        {{ render_single_comment(comment, github_user) }}
    {% endfor %}
{% endmacro %}

{% macro render_container(post, comment_per_page=10, github_user=None) %}
    {% set comments = post.comments[:comment_per_page] %}
    {% set n_comments = post.n_comments %}
    {% set post_id = post.id %}
    <div class="gitment-container gitment-root-container">
        <div class="gitment-container gitment-comments-container">
            {% if comments %}
                <ul class="gitment-comments-list">
                    {{ render_comments(comments, github_user) }}
                </ul>

                <ul class="gitment-comments-pagination">
                    <li class="gitment-comments-page-item gitment-hidden prev">
                        Previous
                    </li>
                    {% set n_pages = n_comments//comment_per_page %}
                    {% for page in range(n_pages if not n_comments % comment_per_page else (n_pages + 1)) %}
                        <li class="gitment-comments-page-item {{ 'gitment-selected' if not page else '' }}">
                            {{ page + 1 }}
                        </li>
                    {% endfor %}

                    <li class="gitment-comments-page-item {{ 'gitment-hidden' if n_comments <= comment_per_page else '' }} next">
                        Next
                    </li>
                </ul>
            {% else %}
                <div class="gitment-comments-empty">还没有评论</div>
            {% endif %}
        </div>
        <div class="gitment-container gitment-editor-container">
            <a class="gitment-editor-avatar"
               href="{{ github_user['link'] if github_user else '/oauth/post/'+post_id|string }}">
                {% if github_user %}
                    <img class="gitment-editor-avatar-img"
                         src="{{ github_user['picture'] }}">
                {% else %}
                    <svg class="gitment-github-icon"
                         xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50">
                        <path d="M25 10c-8.3 0-15 6.7-15 15 0 6.6 4.3 12.2 10.3 14.2.8.1 1-.3 1-.7v-2.6c-4.2.9-5.1-2-5.1-2-.7-1.7-1.7-2.2-1.7-2.2-1.4-.9.1-.9.1-.9 1.5.1 2.3 1.5 2.3 1.5 1.3 2.3 3.5 1.6 4.4 1.2.1-1 .5-1.6 1-2-3.3-.4-6.8-1.7-6.8-7.4 0-1.6.6-3 1.5-4-.2-.4-.7-1.9.1-4 0 0 1.3-.4 4.1 1.5 1.2-.3 2.5-.5 3.8-.5 1.3 0 2.6.2 3.8.5 2.9-1.9 4.1-1.5 4.1-1.5.8 2.1.3 3.6.1 4 1 1 1.5 2.4 1.5 4 0 5.8-3.5 7-6.8 7.4.5.5 1 1.4 1 2.8v4.1c0 .4.3.9 1 .7 6-2 10.2-7.6 10.2-14.2C40 16.7 33.3 10 25 10z"></path>
                    </svg>
                {% endif %}
            </a>

            <div class="gitment-editor-main">
                <div class="gitment-editor-header">
                    <nav class="gitment-editor-tabs">
                        <button class="gitment-editor-tab write gitment-selected">
                            输入
                        </button>
                        <button class="gitment-editor-tab preview">预览
                        </button>
                    </nav>
                    <div class="gitment-editor-login">
                        {% if not github_user %}
                            <a class="gitment-editor-login-link"
                               href="{{ '/oauth/post/'+post_id|string }}">Login</a>
                        {% else %}
                            <a class="gitment-editor-logout-link">{{ github_user['username'] }}</a>
                        {% endif %}
                    </div>
                </div>
                <div class="gitment-editor-body">
                    <div class="gitment-editor-write-field">
          <textarea placeholder="评价一下吧" title=""
                  {% if not github_user %}
                    disabled
                  {% endif %}></textarea>
                    </div>
                    <div class="gitment-editor-preview-field gitment-hidden">
                        <div class="gitment-editor-preview gitment-markdown">
                            空空如也
                        </div>
                    </div>
                </div>
            </div>
            <div class="gitment-editor-footer">
                <a class="gitment-editor-footer-tip"
                   href="https://guides.github.com/features/mastering-markdown/"
                   target="_blank">
                    支持 Markdown 语法
                </a>
                <button class="gitment-editor-submit" title="">评论</button>
            </div>
        </div>
    </div>

{% endmacro %}

app/templates/index.html
{% extends "base.html" %}

{% block more_head %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/index.min.css') }}">
{% endblock %}

{% block content %}
    <div class="{{ post-list if SHOW_PROFILE else '' }}">
        <div class="recent-posts">
            {% for post in posts %}
                <article class="recent-post-item">
                    <a class="title" href="{{ post.url }}">
                        <h2>{{ post.title }}</h2>
                    </a>
                    <div class="post-meta">
                        <time class="time"
                              datetime="{{ post.created_at.strftime('%Y-%m-%dT%H:%M:%S.%fZ') }}">
                            {{ post.created_at.strftime('%Y-%m-%d') }}
                        </time>
                        <span class="slash">/</span>

                        <ul class="index-tag-list">
                            {% for tag in post.tags %}
                                <li class="index-tag-list-item"><a
                                        class="index-tag-list-link"
                                        href="{{ tag.url }}">{{ tag.name }}</a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                    <div class="post-excerpt">
                        <p>{{ post.excerpt }}</p>
                    </div>

                    <a class="more" href="{{ post.url }}"> 阅读全文 〉</a>
                </article>
            {% endfor %}
        </div>
    </div>

    {% if SHOW_PROFILE %}
        <section id="sidebar">

            <div class="short-about">
                <img id="avatar_pic"
                     src="{{ url_for('static', filename='upload/' + profile.avatar) }}">
                <p>{{ profile.intro }}</p>

                <!-- SNS Link -->
                <ul class="list-inline">
                    {% for sns in ('github', 'linkedin') %}
                        <li><a target="_blank"
                               href="{{ profile|getattr(sns + '_url') }}">
            <span class="fa-stack fa-lg">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-{{ sns }} fa-stack-1x fa-inverse"></i>
            </span>
                        </a>
                        </li>

                    {% endfor %}
                </ul>
            </div>
        </section>
    {% endif %}
{% endblock %}

{% block pagination %}
    <nav class="page-nav text-center">
        {% if paginator.has_prev %}
            <a class="extend prev" rel="prev"
               href="{{ url_for('blog.page', ident=paginator.prev_num) }}">
                <</a>
        {% endif %}

        {% for page in paginator.iter_pages() %}
            {% if page %}
                {% if page == paginator.page %}
                    <span class="page-number current">{{ page }}</span>
                {% else %}
                    <a class="page-number"
                       href="{{ url_for('blog.page', ident=page) }}">{{ page }}</a>
                {% endif %}
            {% else %}
                <span class="ellipsis">...</span>
            {% endif %}
        {% endfor %}

        {% if paginator.has_next %}
            <a class="extend next" rel="next"
               href="{{ url_for('blog.page', ident=paginator.next_num) }}">> </a>
        {% endif %}
    </nav>
{% endblock %}

app/templates/post.html
{% extends 'base.html' %}

{% import 'utils.html' as utils %}

{% block more_head %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/post.min.css') }}">
    <meta name="post_id" content="{{ post.id }}">
{% endblock %}

{% block content %}
    <div class="post-container">
        <article class="post" id="post">
            <header class="post-header text-center">
                <h1 class="title">
                    {{ post.title }}
                </h1>
                <span>
        <time class="time"
              datetime="{{ post.created_at.strftime('%Y-%m-%dT%H:%M:%S.%fZ') }}">
          {{ post.created_at.strftime('%Y-%m-%d') }}
        </time>
      </span>
                <span class="slash">/</span>
                <span class="post-meta">
        <span class="post-tags">
          <ul class="article-tag-list">
              {% for tag in post.tags %}
                  <li class="article-tag-list-item">
              <a class="article-tag-list-link"
                 href="{{ tag.url }}">{{ tag.name }}</a>
            </li>
              {% endfor %}

          </ul>
        </span>
      </span>
            </header>

            <div class="post-content">
                {{ post.html_content|safe }}
            </div>

        </article>
        <div class="toc-container">
            {{ post.toc|safe }}
        </div>
    </div>

    <div class="social-sharer" data-title="{{ post.title }}"
         date-url="{{ post.url }}"
         data-services="wechat,weibo,douban,yingxiang,linkedin"></div>

    {% if related_posts %}
        <ul id="related">
            {% for post in related_posts %}
                <li>
                    <a href="{{ post.url }}"
                       title="{{ post.title }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <div id="reactions-container">
        {{ utils.render_react_container(stats, reaction_type) }}
    </div>

    {{ utils.render_comment_container(post, 10, github_user, liked_comment_ids) }}

    <div class="copyright">
        <span>本作品采用</span>
        <a href="https://creativecommons.org/licenses/by/4.0/">知识共享署名 4.0
            国际许可协议</a>
        <span>进行许可。 转载时请注明原文链接。</span>
    </div>

    <div class="post-nav">
    </div>
{% endblock %}

{% block pagination %}

{% endblock %}

{% block bottom_script %}
    <script src="{{ url_for('static', filename='dist/blog/blog.js') }}"></script>
{% endblock %}

app/templates/search.html
{% extends 'base.html' %}

{% block content %}
    <article class="post page" id="page">
        <header class="post-header text-center">
        </header>
        <div class="post-content">
            <div class="search-content">
                <form class="pure-form" _lpchecked="1">
                    <input type="text" id="local-search-input" name="q"
                           results="0" autocomplete="off" placeholder="搜索"
                           class="pure-input pure-input-1">
                </form>
                <div id="local-search-result">
                    <ul class="search-result-list">
                        {% for post in [] %}
                            <li><a href="{{ post.url }}"
                                   class="search-result-title">{{ post.title }}</a>
                                <p class="search-result">{{ post.excerpt }}</p>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

{% block pagination %}

{% endblock %}

{% block bottom_script %}
    <script src="{{ url_for('static', filename='dist/blog/search.js') }}"></script>
{% endblock %}

app/templates/tag.html
{% extends 'base.html' %}

{% block content %}
    <div class="page tag-page" id="tag">
        <h3 title="{{ tag.name }}下的文章">{{ tag.name }}</h3>
        {% for post in posts %}
            <div class="tag-item">
                <a href="{{ post.url }}">
                    {{ post.title }}
                </a>
                <time class="time"
                      datetime="{{ post.created_at.strftime('%Y-%m-%dT%H:%M:%S.%fZ') }}">
                    {{ post.created_at.strftime('%Y-%m-%d') }}
                </time>
            </div>
        {% endfor %}

    </div>
{% endblock %}

{% block pagination %}

{% endblock %}

app/templates/tags.html
{% extends 'base.html' %}

{% block content %}
    <article class="post page" id="page">
        <div class="post-content">
            <ul class="tag-list">
                {% for tag, count in tags %}
                    <li class="tag-list-item">
                        <a class="tag-list-link" href="{{ tag.url }}">
                            {{ tag.name }}</a>
                        <span class="tag-list-count">{{ count }}</span>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </article>
{% endblock %}

{% block pagination %}

{% endblock %}